[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE", "src/BSCValidatorSet_abi.json"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "bridge-pangoro-kiln"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.7"

[[bin]]
name = "bridge-pangoro-kiln"
path = "src/main.rs"

[dependencies]
color-eyre = "0.5"
tracing    = "0.1"

reqwest = { version = "0.11", features = ["json"] }
tokio   = { version = "1", features = ["full"] }

serde     = { version = "1", features = ["derive"] }
structopt = "0.3"
strum     = { version = "0.21", features = ["derive"] }

futures  = "0.3.21"
lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage  = "0.4"
web3     = { git = "https://github.com/tomusdrw/rust-web3", branch = "master", features = ["signing"] }

support-common   = { path = "../../../frame/supports/support-common" }
support-lifeline = { path = "../../../frame/supports/support-lifeline" }
support-terminal = { path = "../../../frame/supports/support-terminal" }

component-http-client = { path = "../../../frame/components/http-client" }
