[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE", "src/BSCValidatorSet_abi.json"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "bridge-pangoro-kiln"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.6.1"

[[bin]]
name = "bridge-pangoro-kiln"
path = "src/main.rs"

[dependencies]
color-eyre  = "0.5"
tracing     = "0.1"
async-trait = "0.1"

reqwest = { version = "0.11", features = ["json", "stream"] }
tokio   = { version = "1", features = ["full"] }

serde     = { version = "1", features = ["derive"] }
structopt = "0.3"
strum     = { version = "0.21", features = ["derive"] }

bytes     = "1.0"
futures   = "0.3.21"
hex       = "0.4"
lifeline  = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage   = "0.4"
secp256k1 = { version = "0.21" }
web3      = { version = "0.18.0", features = ["signing"] }
hamming   = "0.1"
rlp       = "0.5.1"

support-common   = { path = "../../../frame/supports/support-common" }
support-lifeline = { path = "../../../frame/supports/support-lifeline" }
support-terminal = { path = "../../../frame/supports/support-terminal" }
bridge-e2e-traits       = { path = "../../../frame/traits/bridge-e2e" }

component-http-client = { path = "../../../frame/components/http-client" }
