[package]
name          = "bridge-s2s-traits"
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.7.1"


[dependencies]
thiserror   = "1"
async-trait = "0.1"

#num-traits     = "0.2"
serde          = { version = "1.0.124", features = ["derive"] }
codec          = { package = "parity-scale-codec", version = "2" }
scale-info     = { version = "1.0.0", features = ["bit-vec"] }
jsonrpsee-core = { version = "0.8", features = ["client"] }

sp-core               = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.5" }
sp-runtime            = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.5" }

bp-runtime            = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.5" }
bp-messages           = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.5" }
bridge-runtime-common = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.5" }
bp-header-chain       = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.5" }

client-common-traits = { path = "../client-common" }

array-bytes = { optional = true, version = "2" }
subxt       = { optional = true, git = "https://github.com/darwinia-network/subxt.git", branch = "darwinia-v0.12.5" }


[features]
default  = []
bridge-parachain = []
advanced-types = [
  "array-bytes",
  "subxt",
]
