[workspace]
members = [
  "bridge",
  "client-darwinia",
  "client-crab",
]

[patch.crates-io]
evm           = { git = "https://github.com/darwinia-network/evm", branch = "darwinia-v0.12.0" }
evm-gasometer = { git = "https://github.com/darwinia-network/evm", branch = "darwinia-v0.12.0" }
evm-runtime   = { git = "https://github.com/darwinia-network/evm", branch = "darwinia-v0.12.0" }