[package]
name = "bridge-darwinia-crab"
version = "0.8.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
tracing     = "0.1"
color-eyre  = "0.6"
structopt   = "0.3"
async-trait = "0.1"
strum       = { version = "0.24", features = ["derive"] }
serde       = { version = "1", features = ["derive"] }
tokio       = { version = "1", features = ["full"] }

bin-s2s         = { path = "../../assistants/bin-s2s", features = ["para-with-para"] }
subquery        = { path = "../../assistants/subquery" }
support-common  = { path = "../../frame/supports/support-common" }
support-toolkit = { path = "../../frame/supports/support-toolkit" }
support-types   = { path = "../../frame/supports/support-types" }

bridge-s2s-traits    = { path = "../../traits/bridge-s2s" }
feemarket-s2s-traits = { path = "../../traits/feemarket-s2s" }
client-common-traits = { path = "../../traits/client-common" }

client-darwinia = { path = "../../assistants/client-darwinia", features = [ "bridge-darwinia-crab", "feemarket-darwinia-crab" ]}
client-crab     = { path = "../../assistants/client-crab", features = [ "bridge-darwinia-crab", "feemarket-darwinia-crab" ]}
client-polkadot = { path = "../../assistants/client-polkadot", features = [ "bridge-darwinia-crab" ] }
client-kusama   = { path = "../../assistants/client-kusama", features = [ "bridge-darwinia-crab" ] }
