[package]
name = "task-darwinia-ethereum"
version = "0.4.7"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
    "Cargo.toml",
    "**/*.rs",
    "README.md",
    "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
async-trait = "0.1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
codec = { package = "parity-scale-codec", version = "2.0.0" }
colored = "2.0"

lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage = "0.4"

web3 = { git = "https://github.com/wuminzhe/rust-web3.git", branch = "master", features = ["signing"] }
microkv = { git = "https://github.com/fewensa/microkv.git", branch = "master" }
array-bytes = "1.1.0"

async-recursion = "0.3.2"
substrate-subxt = { git = "https://github.com/darwinia-network/substrate-subxt.git", tag = "darwinia-v0.11.3-patch.1" }

tokio = { version = "1", features = ["full"] }

bridge-traits = { path = "../../traits" }
linked-darwinia = { path = "../linked-darwinia" }

component-state = { path = "../../components/state" }
component-ethereum = { path = "../../components/ethereum" }
component-shadow = { path = "../../components/shadow" }
component-darwinia-subxt = { path = "../../components/client-darwinia-subxt" }
component-thegraph-liketh = { path = "../../components/thegraph-liketh" }
component-http-client = { path = "../../components/http-client" }

support-tracker = { path = "../../supports/support-tracker" }
support-ethereum = { path = "../../supports/support-ethereum" }
support-keep = { path = "../../supports/support-keep" }


