specVersion: 0.2.0
name: bridge-s2s-crab-parachain
version: 0.0.4
description: S2S bridge crab parachain subql
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql

network:
  endpoint: wss://crab-parachain-rpc.darwinia.network
  genesisHash: '0xeac895d7768b17837a9c3a9f0280c01502c3ef40193df923490a0fa9c60ea076'

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleCall
          kind: substrate/CallHandler

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabMessages
            method: MessageAccepted

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabDispatch
