[package]
name = "component-darwinia-subxt"
version = "0.4.6"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
    "Cargo.toml",
    "**/*.rs",
    "README.md",
    "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
anyhow = "1"
thiserror = "1"
log = "0.4"
async-trait = "0.1"
array-bytes = "1.1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive", "full"] }
web3 = { git = "https://github.com/wuminzhe/rust-web3.git", branch = "master", features = ["signing"] }
secp256k1 = { version = "0.20", features = ["recovery"] }

jsonrpsee-types = "0.3"
substrate-subxt = { git = "https://github.com/darwinia-network/substrate-subxt.git", tag = "darwinia-v0.11.3" }
substrate-subxt-proc-macro = { git = "https://github.com/darwinia-network/substrate-subxt.git", tag = "darwinia-v0.11.3" }

frame-support = { package = "frame-support", git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.3" }
pallet-indices = { package = "pallet-indices", git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.3" }
pallet-im-online = { package = "pallet-im-online", git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.3" }

bridge-traits = { path = "../../traits" }
support-ethereum = { path = "../../supports/support-ethereum" }
bridge-primitives = { path = "../../primitives" }
