[package]
name = "client-pangolin-parachain"
version = "0.5.7"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
tracing     = "0.1"
thiserror   = "1"
array-bytes = "1.4"

serde       = { version = "1", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2" }
subxt        = { git = "https://github.com/darwinia-network/subxt.git", branch = "darwinia-v0.12.2" }

support-toolkit  = { path = "../../../frame/supports/support-toolkit" }
