specVersion: 0.2.0
name: bridge-subql-darwinia
description: Darwinia network
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7200000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            - module: ethereumRelayAuthorities
              method: MMRRootSigned
            - module: ethereumRelayAuthorities
              method: ScheduleMMRRoot
            - module: ethereumRelayAuthorities
              method: ScheduleAuthoritiesChange
            - module: ethereumRelayAuthorities
              method: AuthoritiesChangeSigned
        - handler: handleCall
          kind: substrate/CallHandler

network:
  genesisHash: '0x729cb8f2cf428adcf81fe69610edda32c5711b2ff17de747e8604a3587021db8'
  endpoint: wss://rpc.darwinia.network/
  chaintypes:
    file: ./dist/chaintypes.js

