[package]
name = "darwinia-bridger"
version = "0.7.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"


[[bin]]
name = "bridger"
path = "src/main.rs"

[dependencies]

colored = "2"
requestty = "0.1"

structopt = "0.3"

tracing    = "0.1"
color-eyre = "0.6"
term-table = "1.3"

strum = { version = "0.24", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "1"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
cargo-util = "0.1"
sys-info = "0.9"
sysinfo = "0.22"
zip = "0.5"

microkv = { git = "https://github.com/fewensa/microkv.git", branch = "master" }

support-common   = { path = "../supports/support-common" }
support-types    = { path = "../supports/support-types" }
support-terminal = { path = "../supports/support-terminal" }
component-state  = { path = "../components/state" }
