[package]
name = "client-darwinia"
version = "0.5.2"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
tracing = "0.1"
color-eyre = "0.5"

async-trait = "0.1"

codec                  = { package = "parity-scale-codec", version = "2.3.1" }

relay-substrate-client = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
relay-utils            = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
bp-messages            = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
bp-runtime             = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
messages-relay         = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }

## Bridge dependencies
darwinia-runtime           = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.12.0" }
darwinia-common-primitives = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.12.0" }
darwinia-bridge-primitives = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.12.0" }
darwinia-bridge-ethereum   = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "darwinia-v0.12.0" }
dp-fee                     = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "darwinia-v0.12.0" }

## Substrate Dependencies
frame-system               = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
frame-support              = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
sp-keyring                 = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }

