[package]
name          = "substrate-relay"
version       = "0.3.3"
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
repository    = "https://github.com/darwinia-network/bridger"
license       = "MIT"
documentation = "https://docs.rs/bridger"
homepage      = "https://github.com/darwinia-network/bridger"
include = [
    "Cargo.toml",
    "**/*.rs",
    "README.md",
    "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[[bin]]
name = "substrate-relay"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"

futures = "0.3"
structopt = "0.3"

log = "0.4"
env_logger = "0.8"

## chain relay
[dependencies.chain-relay]
path = "../relays/chain-relay"
features = [
    "millau",
    "pangolin"
]

