[package]
name = "support-command-kv"
version = "0.6.3"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]

structopt = "0.3"

tracing = "0.1"
color-eyre = "0.5"
term-table = "1.3"

strum = { version = "0.21", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

microkv = { git = "https://github.com/fewensa/microkv.git", branch = "master" }

support-common     = { path = "../support-common" }
support-terminal   = { path = "../support-terminal" }

component-state    = { path = "../../components/state" }
toml = "0.5"
