[package]
name = "component-pangolin-s2s"
version = "0.4.8"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
log = "0.4"

bridge-traits = { path = "../../traits" }

codec                  = { package = "parity-scale-codec", version = "2.0.0" }
headers-relay          = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.11.7" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.11.7" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.11.7" }
messages-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.11.7" }
bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.11.7" }
bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.11.7" }

## Bridge dependencies
pangolin-runtime         = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "xavier-2.7.1" }
drml-common-primitives   = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "xavier-2.7.1" }
drml-bridge-primitives   = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "xavier-2.7.1" }
darwinia-bridge-ethereum = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "xavier-2.7.1" }
dp-fee                   = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "xavier-2.7.1" }



## Substrate Dependencies
frame-system               = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.11.7" }
frame-support              = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.11.7" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.11.7" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.11.7" }
sp-keyring                 = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.11.7" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.11.7" }


[dev-dependencies]
anyhow       = "1"
futures-test = "0.3"
tokio        = { version = "1", features = ["time"] }
codec        = { package = "parity-scale-codec", version = "2.2.0" }

