specVersion: 0.2.0
name: bridge-s2s-pangoro
version: 0.0.4
description: S2S bridge pangoro subql
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql

network:
  genesisHash: '0xf37f31c4481e3c937ad40b672c561d0c0b1fb70b40e51a0d56dad30d60e4db58'
  endpoint: wss://pangoro-rpc.darwinia.network
  dictionary: https://api.subquery.network/sq/darwinia-network/pangoro-dictionary

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 2500646
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            - module: grandpa
              method: NewAuthorities
            - module: bridgePangolinMessages
              method: MessageAccepted
            - module: bridgePangolinDispatch
        - handler: handleCall
          kind: substrate/CallHandler
