[package]
name          = "client-common-traits"
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.7.3"

[dependencies]
bp-runtime        = { git = "https://github.com/darwinia-network/darwinia-messages-substrate", branch = "polkadot-v0.9.37" }

subxt            = { optional = true, git = "https://github.com/darwinia-network/subxt", branch = "polkadot-v0.9.37" }
bp-darwinia-core = { optional = true, git = "https://github.com/darwinia-network/darwinia-messages-substrate", branch = "polkadot-v0.9.37" }
sp-runtime       = { optional = true, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
codec            = { optional = true, package = "parity-scale-codec", version = "3" }



[features]

subxt-darwinia = [
  "subxt",
  "bp-darwinia-core",
  "sp-runtime",
  "codec",
]

