[package]
name = "component-subscan"
version = "0.5.5"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
tracing = "0.1"
thiserror = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde-hex = "0.1"
serde-aux = "0.6"

reqwest = { version = "0.11", features = ["rustls-tls", "json", "blocking"] }
