[package]
name = "task-pangolin-millau"
version = "0.3.3"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
    "Cargo.toml",
    "**/*.rs",
    "README.md",
    "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
anyhow = "1.0"
log = "0.4"
custom_derive = "0.1"
enum_derive = "0.1"
codec = { package = "parity-scale-codec", version = "2.0.0" }

lifeline = "0.6"
postage = "0.4"

bridge-standard = { path = "../../bridge-standard" }
bridge-component = { path = "../../bridge-component" }

external-s2s = { path = "../../bridge-external/external-s2s", features = [ "millau", "pangolin" ] }
chain-pangolin = { path = "../../bridge-chain/chain-pangolin" }
chain-millau = { path = "../../bridge-chain/chain-millau" }

# Bridge dependencies

relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.2" }
bp-header-chain        = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.2" }
bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.2" }

# Substrate Dependencies

sp-core             = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.2" }

[dev-dependencies]
