[package]
name = "bridge-darwinia-crab"
version = "0.5.2"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
tracing = "0.1"
color-eyre = "0.5"

async-trait = "0.1"

tokio       = { version = "1", features = ["full"] }
colored     = "2"
structopt   = "0.3"
strum       = { version = "0.21", features = ["derive"] }

codec = { package = "parity-scale-codec", version = "2.3.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
futures = "0.3"
futures-timer = "3"

lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage = "0.4"


## Substrate Dependencies

frame-support       = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
sp-core             = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
sp-trie             = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }
sp-version          = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.0" }

## bridge common

bp-runtime             = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
bp-messages            = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
bp-header-chain        = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
relay-substrate-client = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
substrate-relay-helper = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
relay-utils            = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
bridge-runtime-common  = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
pallet-bridge-messages = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }
messages-relay         = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.0" }


## component
client-darwinia        = { path = "../client-darwinia" }
client-crab            = { path = "../client-crab" }
component-subscan      = { path = "../../../frame/components/subscan" }

## support
support-common     = { path = "../../../frame/supports/support-common" }
support-lifeline   = { path = "../../../frame/supports/support-lifeline" }
support-terminal   = { path = "../../../frame/supports/support-terminal" }

## darwinia common
darwinia-bridge-primitives = { git = "https://github.com/darwinia-network/darwinia.git", branch = "xavier-0.12.0" }
darwinia-common-primitives = { git = "https://github.com/darwinia-network/darwinia.git", branch = "xavier-0.12.0" }
darwinia-common-runtime    = { git = "https://github.com/darwinia-network/darwinia.git", branch = "xavier-0.12.0" }

## darwinia
darwinia-runtime               = { git = "https://github.com/darwinia-network/darwinia.git", branch = "xavier-0.12.0" }

## crab
crab-runtime                   = { git = "https://github.com/darwinia-network/darwinia.git", branch = "xavier-0.12.0" }

