[package]
name = "bridge-darwinia-crab"
version = "0.6.1"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
tracing     = "0.1"
color-eyre  = "0.5"

array-bytes = "2"
tokio       = { version = "1", features = ["full"] }

structopt = "0.3"
strum     = { version = "0.21", features = ["derive"] }
serde     = { version = "1", features = ["derive"] }

lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage  = "0.4"

support-common     = { path = "../../../frame/supports/support-common" }
support-lifeline   = { path = "../../../frame/supports/support-lifeline" }
support-toolkit    = { path = "../../../frame/supports/support-toolkit" }

bridge-s2s-traits   = { path = "../../../frame/traits/bridge-s2s" }
client-darwinia     = { path = "../../../frame/assistants/client-darwinia", features = [ "bridge-s2s-crab", "feemarket-s2s-crab" ]}
client-crab         = { path = "../../../frame/assistants/client-crab", features = [ "bridge-s2s-darwinia", "feemarket-s2s-darwinia" ]}
subquery-s2s        = { path = "../../../frame/assistants/subquery-s2s" }
relay-s2s           = { path = "../../../frame/assistants/relay-s2s" }
feemarket-s2s       = { path = "../../../frame/assistants/feemarket-s2s" }
