[package]
name = "chain-relay"
version = "0.3.3"
authors    = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
    "Cargo.toml",
    "**/*.rs",
    "README.md",
    "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]

anyhow = "1.0"
log = "0.4"
async-std = "1.9.0"
async-trait = "0.1"
paste = "1.0"
futures = "0.3"
getset = "0.1"

serde = "1"
serde_derive = "1"

codec = { package = "parity-scale-codec", version = "2.0.0" }
hex = "0.4"
num-format = "0.4"
num-traits = "0.2"
custom_derive = "0.1"
enum_derive = "0.1"

# chain

## pangolin
pangolin-runtime = { git = "https://github.com/darwinia-network/darwinia-common", branch = "s2s", optional = true }
drml-primitives = { git = "https://github.com/darwinia-network/darwinia-common", branch = "s2s", optional = true  }
pangolin-constants = { git = "https://github.com/darwinia-network/darwinia-common", branch = "s2s", optional = true  }
pangolin-bridge-primitives = { git = "https://github.com/darwinia-network/darwinia-common", branch = "s2s", optional = true  }
pangolin-runtime-system-params = { git = "https://github.com/darwinia-network/darwinia-common", branch = "s2s", optional = true }
pangolin-bridge-relay-client-definition = { path = "../client-pangolin", optional = true }


## millau
millau-runtime = { git = "https://github.com/darwinia-network/darwinia-launch", branch = "main", optional = true }
bp-millau = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s", optional = true }
relay-millau-client = { path = "../client-millau", optional = true }

# Bridge dependencies

bp-header-chain = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
bp-messages = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
bp-runtime = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
bp-message-dispatch = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
bridge-runtime-common = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
finality-grandpa = { version = "0.14.0" }
finality-relay = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
headers-relay = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
messages-relay = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
pallet-bridge-messages = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
relay-utils = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }

# Substrate Dependencies

frame-support = { git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }
sp-core = { git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }
sp-trie = { git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }
sp-version = { git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }

[dev-dependencies]
sp-keyring = { git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }
hex-literal = "0.3"

[features]
default = []
millau = [
    "millau-runtime",
    "relay-millau-client",
    "bp-millau",
]
pangolin = [
    "pangolin-runtime",
    "pangolin-bridge-relay-client-definition",
    "drml-primitives",
    "pangolin-constants",
    "pangolin-bridge-primitives",
    "pangolin-runtime-system-params",
]
