specVersion: 0.2.0
name: parachain-rococo-subql
version: 0.0.4
description: Rococo parachain subql
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql
network:
  endpoint: wss://rococo-rpc.polkadot.io/
  genesisHash: '0x6408de7737c59c238890533af25896a2c20608d8b380bb01029acb392781063e'
  # dictionary: https://api.subquery.network/sq/subquery/kusama-dictionary
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            - module: paraInclusion
              method: CandidateIncluded
        - handler: handleCall
          kind: substrate/CallHandler
