[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE", "src/BSCValidatorSet_abi.json"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "bridge-pangolin-goerli"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.7.3"

[[bin]]
name = "bridge-pangolin-goerli"
path = "src/main.rs"

[dependencies]
color-eyre  = "0.6"
tracing     = "0.1"
tokio       = { version = "1", features = ["full"] }
serde       = { version = "1", features = ["derive"] }
structopt   = "0.3"
web3        = { version = "0.18", features = ["signing"] }
array-bytes = "6"
secp256k1   = "0.21"

support-common     = { path = "../../../frame/supports/support-common" }
support-command-kv = { path = "../../../frame/supports/support-command-kv" }
support-etherscan  = { path = "../../../frame/supports/support-etherscan" }
component-state    = { path = "../../../frame/components/state" }

subquery              = { path = "../../../assistants/subquery", features = [ "bridge-ethv2" ] }
client-contracts      = { path = "../../../assistants/client-contracts" }
client-pangolin        = { path = "../../../assistants/client-pangolin", features = [ "bridge-ethv2" ] }
thegraph              = { path = "../../../assistants/thegraph", features = [ "bridge-ethv2" ] }

bridge-e2e-traits     = { path = "../../../traits/bridge-e2e" }
relay-e2e             = { path = "../../../assistants/relay-e2e" }
bin-e2e               = { path ="../../../assistants/bin-e2e" }
