specVersion: 0.2.0
name: parachain-kusama-subql
version: 0.0.4
description: Kusama parachain subql
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql

network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  dictionary: https://api.subquery.network/sq/subquery/kusama-dictionary

dataSources:
  - kind: substrate/Runtime
    startBlock: 11905712
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            - module: paraInclusion
              method: CandidateIncluded
        - handler: handleCall
          kind: substrate/CallHandler
