[package]
name = "bridge-darwinia-ethereum"
version = "0.5.7"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]

tracing = "0.1"
color-eyre = "0.5"

tokio = { version = "1", features = ["full"] }

colored     = "2"
structopt   = "0.3"
strum       = { version = "0.21", features = ["derive"] }

lifeline    = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage     = "0.4"

array-bytes = "1.4"
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
codec       = { package = "parity-scale-codec", version = "2" }

rand        = "0.8"


web3    = { git = "https://github.com/wuminzhe/rust-web3.git", branch = "master", features = ["signing"] }
microkv = { git = "https://github.com/fewensa/microkv.git", branch = "master" }


client-darwinia    = { path = "../../../frame/assistants/client-darwinia", features = ["ethlike-v1"] }

support-common     = { path = "../../../frame/supports/support-common" }
support-lifeline   = { path = "../../../frame/supports/support-lifeline" }
support-terminal   = { path = "../../../frame/supports/support-terminal" }
support-tracker    = { path = "../../../frame/supports/support-tracker" }
support-command-kv = { path = "../../../frame/supports/support-command-kv" }

component-ethereum        = { path = "../../../frame/components/ethereum" }
component-http-client     = { path = "../../../frame/components/http-client" }
component-state           = { path = "../../../frame/components/state" }

thegraph-liketh = { path = "../../../frame/assistants/thegraph-liketh" }
subquery-d2e    = { path = "../../../frame/assistants/subquery-d2e" }
shadow-liketh   = { path = "../../../frame/assistants/shadow-liketh" }
