[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "client-crab"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.7"

[dependencies]
thiserror = "1"
tracing   = "0.1"

serde      = { version = "1", features = ["derive"] }
serde_json = "1"

array-bytes     = "1.4"
codec           = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full"] }
futures-util    = "0.3.14"
jsonrpsee       = { version = "0.8.0", features = ["async-client", "client-ws-transport"] }
sp-core         = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.2" }
subxt           = { git = "https://github.com/darwinia-network/subxt.git", branch = "darwinia-v0.12.2" }
support-toolkit = { path = "../../../frame/supports/support-toolkit" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
