[package]
name = "chain-relay"
version = "0.3.3"
authors    = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
    "Cargo.toml",
    "**/*.rs",
    "README.md",
    "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]

anyhow = "1.0"
log = "0.4"
async-std = "1.9.0"
async-trait = "0.1"
paste = "1.0"
futures = "0.3"
getset = "0.1"

serde = "1"
serde_derive = "1"

codec = { package = "parity-scale-codec", version = "2.0.0" }
hex = "0.4"
num-format = "0.4"
num-traits = "0.2"
custom_derive = "0.1"
enum_derive = "0.1"

# chain

## pangolin
pangolin-runtime                        = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s", optional = true }
drml-primitives                         = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s", optional = true }
pangolin-constants                      = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s", optional = true }
pangolin-bridge-primitives              = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s", optional = true }
pangolin-runtime-system-params          = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s", optional = true }
pangolin-bridge-relay-client-definition = { path = "../client-pangolin", optional = true }


## millau
millau-runtime      = { git = "https://github.com/darwinia-network/darwinia-launch.git", branch = "s2s", optional = true }
millau-primitives   = { git = "https://github.com/darwinia-network/darwinia-launch.git", branch = "s2s", optional = true }
relay-millau-client = { path = "../client-millau", optional = true }

# Bridge dependencies

bp-header-chain        = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bp-message-dispatch    = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bridge-runtime-common  = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
finality-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
headers-relay          = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
messages-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
pallet-bridge-messages = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
finality-grandpa       = { version = "0.14.0" }

# Substrate Dependencies

frame-support       = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-core             = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-trie             = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-version          = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }

[dev-dependencies]
sp-keyring  = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
hex-literal = "0.3"

[features]
default = []
millau = [
    "millau-runtime",
    "relay-millau-client",
    "millau-primitives",
]
pangolin = [
    "pangolin-runtime",
    "pangolin-bridge-relay-client-definition",
    "drml-primitives",
    "pangolin-constants",
    "pangolin-bridge-primitives",
    "pangolin-runtime-system-params",
]
