[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "bridge-pangolin-pangolinparachainalpha"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.7.0"

[dependencies]
tracing    = "0.1"
color-eyre = "0.6"

array-bytes = "2"
tokio       = { version = "1", features = ["full"] }

structopt = "0.3"
strum     = { version = "0.24", features = ["derive"] }
serde     = { version = "1", features = ["derive"] }

lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage  = "0.4"

support-common     = { path = "../../../frame/supports/support-common" }
support-lifeline   = { path = "../../../frame/supports/support-lifeline" }
support-toolkit    = { path = "../../../frame/supports/support-toolkit" }

bridge-s2s-traits         = { path = "../../../frame/traits/bridge-s2s" }
client-pangolin           = { path = "../../../assistants/client-pangolin", features = [ "bridge-s2s-pangolin-parachain-alpha", "feemarket-s2s-pangolin-parachain-alpha" ]}
client-moonbase           = { path = "../../../assistants/client-moonbase", features = [ "bridge-s2s-pangolin" ] }
client-pangolin-parachain = { path = "../../../assistants/client-pangolin-parachain", features = [ "bridge-s2s-pangolin", "feemarket-s2s-pangolin" ] }
subquery                  = { path = "../../../assistants/subquery", features = ["bridge-parachain"] }
relay-s2s                 = { path = "../../../assistants/relay-s2s", features = [ "bridge-parachain" ] }
feemarket-s2s             = { path = "../../../assistants/feemarket-s2s" }
