[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "subquery-s2s"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.5"

[dependencies]
include_dir = "0.7.2"
thiserror   = "1.0"
tracing     = "0.1"

async-trait = "0.1"
hex         = "0.4"
serde       = { version = "1.0", features = ["derive"] }
serde-aux   = "0.6"
serde-hex   = "0.1"
strum       = { version = "0.21", features = ["derive"] }

gql_client = "1"
