specVersion: 0.2.0
name: bridge-subql-pangolin
description: Pangolin network
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 119850
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            - module: ethereumRelayAuthorities
              method: MMRRootSigned
            - module: ethereumRelayAuthorities
              method: ScheduleMMRRoot
            - module: ethereumRelayAuthorities
              method: ScheduleAuthoritiesChange
            - module: ethereumRelayAuthorities
              method: AuthoritiesChangeSigned
        - handler: handleCall
          kind: substrate/CallHandler

network:
  genesisHash: '0xce44bd16fc276f9e457b452577b6c2678e57768260012af127479fed806da7e7'
  endpoint: wss://pangolin-rpc.darwinia.network
#  chaintypes:
#    file: ./types.yaml
