[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "feemarket-ns2s"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.7"

[dependencies]

async-trait = "0.1"
serde       = { version = "1", features = ["derive"] }
thiserror   = "1.0"
tracing     = "0.1"

component-subscan   = { path = "../../components/subscan" }

abstract-bridge-s2s    = { path = "../../abstract/bridge-s2s" }
abstract-feemarket-s2s = { path = "../../abstract/feemarket-s2s" }
support-toolkit        = { path = "../../supports/support-toolkit", features = ["log"] }
