[pangolin]
endpoint             = "ws://pangolin:9944"
signer               = "//Alice"

[rococo]
endpoint             = "ws://rococo-alice:9944"

[pangolin_parachain]
endpoint             = "ws://pangolin-parachain:9944"
signer               = "//Alice"

[relay]
lanes   = ["70616c69"]
para_id = 2105

[index]
pangolin           = { endpoint = "http://graphql-engine-s2s-pangolin:3000" }
rococo             = { endpoint = "http://graphql-engine-s2s-rococo:3000" }
pangolin_parachain = { endpoint = "http://graphql-engine-s2s-pangolin-parachain:3000" }
parachain_rococo   = { endpoint = "http://graphql-engine-parachain-rococo:3000" }
