[pangoro]
endpoint = "https://pangoro-rpc.darwinia.network"
bsc_address = "0x3de59b57461754576d76a76c49797684cbae7834"
private_key = "//Alice"

[chapel]
endpoint = "https://data-seed-prebsc-1-s1.binance.org:8545"

