[darwinia]
endpoint = "wss://rpc.darwinia.network"
signer   = "//Alice"

[crab]
endpoint = "wss://crab-rpc.darwinia.network"
signer   = "//Alice"

[relay]
lanes            = ["00000000"]
enable_mandatory = false

[index]
darwinia = { endpoint = "https://subql.darwinia.network/subql-bridger-darwinia" }
crab     = { endpoint = "https://subql.darwinia.network/subql-bridger-crab" }
