[general]
# Whether to relay beacon chain header to evm chain
enable_beacon_header_relay = true
# Whether to relay sync commit from beacon chain to evm chain
enable_sync_commit_relay = true
# Whether to sign the messages root and relay headers from evm chain to beacon chain
enable_ecdsa_relay = true
# Whether to relay messages from execution chain to evm chain
enable_message_execution_to_evm = true
# Whether to relay messages from evm chain to execution chain
enable_message_evm_to_execution = true
# Max number of messages every delivery
max_message_num_per_relaying = 15
# Minimum seconds between two header relay
header_relay_minimum_interval = 900

[pangolin_evm]
chain_message_committer_address = "0x0f82Dc70C65F62799E6436f41d605756f943140e"
contract_address                = "0x9Ca2b190d84E635F131060319FACc943b0653680"
endpoint                        = "https://pangolin-rpc.darwinia.network"
fee_market_address              = "0x4DBdC9767F03dd078B5a1FC05053Dd0C071Cc005"
inbound_address                 = "0xB59a893f5115c1Ca737E36365302550074C32023"
lane_message_committer_address  = "0x59EA974B74ec6A49338438bCc5d0388E294E4E20"
outbound_address                = "0xAbd165DE531d26c229F9E43747a8d683eAD54C6c"
# private_key in format of 0x... or ...
private_key = "..."
# Max gas price bridger would use, if eth_gasPrice returns a bigger one. Unit is wei.
max_gas_price = 24513218380275

[pangolin_substrate]
endpoint = "wss://pangolin-rpc.darwinia.network"
# private_key in format of 0x... or BIP39 mnemonic code
private_key = "//Alice"

[beacon]
endpoint = "https://lodestar-goerli.chainsafe.io"
# Beacon chain rpc supplier: Nimbus or Lodestar
api_supplier = "Nimbus"

[goerli]
endpoint                  = "https://eth-goerli.g.alchemy.com/v2/3Jsx6GWpt8x8g783OqtWoGSHxIsIji2O"
fee_market_address        = "0x6c73B30a48Bb633DC353ed406384F73dcACcA5C3"
inbound_address           = "0x0F6e081B1054c59559Cf162e82503F3f560cA4AF"
outbound_address          = "0x9B5010d562dDF969fbb85bC72222919B699b5F54"
posa_light_client_address = "0x66aB6f080b37Df0a99687A0bBB65A798bC1067C1"
# private_key in format of 0x... or ...
private_key = "..."
# Max gas price bridger would use, if eth_gasPrice returns a bigger one. Unit is wei.
max_gas_price = 9000000000
# Bridger use etherscan gas oracle to get more appropriate gas price.
# Register to get a free etherescan api key at https://docs.etherscan.io/api-endpoints/gas-tracker
etherscan_api_key = "api_key..."


[index]
evm_chain       = { endpoint = "https://thegraph.darwinia.network/ethv2/subgraphs/name/bridge-pangolin" }
substrate_chain = { endpoint = "https://subql.darwinia.network/subql-bridger-pangolin/" }
