[pangolin]
endpoint = "wss://pangolin-rpc.darwinia.network"
signer = "//Alice"

[pangoro]
endpoint = "wss://pangoro-rpc.darwinia.network"
signer = "//Alice"

[relay]
# substrate-substrate bridger message relay lanes, default use `00000000`
lanes = ["726f6c69"]

[index]
pangolin = { endpoint = "https://api.subquery.network/sq/darwinia-network/subql-bridge-s2s-pangolin" }
pangoro  = { endpoint = "https://api.subquery.network/sq/darwinia-network/subql-bridge-s2s-pangoro" }

