[pangolin]
endpoint             = "wss://pangolin-rpc.darwinia.network"
runtime_version_mode = "Auto"
signer               = "//Alice"

[rococo]
endpoint             = "wss://rococo-rpc.polkadot.io"
runtime_version_mode = "Auto"

[pangolin_parachain]
endpoint             = "wss://pangolin-parachain-rpc.darwinia.network"
runtime_version_mode = "Auto"
signer               = "//Alice"

[relay]
lanes   = ["70616c69"]
para_id = 2105

[index]
pangolin           = { endpoint = "https://api.subquery.network/sq/darwinia-network/subql-bridge-s2s-pangolin" }
rococo             = { endpoint = "https://api.subquery.network/sq/darwinia-network/subql-bridge-s2s-rococo" }
pangolin_parachain = { endpoint = "https://api.subquery.network/sq/fewensa/subql-bridge-s2s-pangolin-parachain" }
parachain_rococo   = { endpoint = "https://api.subquery.network/sq/darwinia-network/subql-parachain-rococo" }
