[crab]
endpoint = "wss://crab-rpc.darwinia.network:443"
signer   = "//Alice"

[kusama]
endpoint = "wss://kusama-rpc.polkadot.io:443"

[crab_parachain]
endpoint = "wss://crab-parachain-rpc.darwinia.network:443"
signer   = "//Alice"

[relay]
lanes            = ["70616372"]
para_id          = 2105
enable_mandatory = false

[index]
crab               = { endpoint = "https://subql.darwinia.network/subql-bridger-crab" }
kusama             = { endpoint = "https://subql.darwinia.network/subql-bridger-kusama" }
crab_parachain     = { endpoint = "https://subql.darwinia.network/subql-bridger-crab-parachain" }

