[darwinia]
endpoint             = "wss://rpc.darwinia.network"
signer               = "//Alice"

[polkadot]
endpoint             = "wss://rpc.polkadot.io"

[darwinia_parachain]
endpoint             = "wss://parachain-rpc.darwinia.network"
signer               = "//Alice"

[relay]
lanes            = ["00000001"]
para_id          = 2046
enable_mandatory = false

[index]
pangolin           = { endpoint = "https://subql.darwinia.network/subql-bridger-darwinia" }
rococo             = { endpoint = "https://subql.darwinia.network/subql-bridger-polkadot" }
pangolin_parachain = { endpoint = "https://subql.darwinia.network/subql-bridger-darwinia-parachain" }
