[pangolin]
endpoint             = "wss://pangolin-rpc.darwinia.network"
signer               = "//Alice"

[rococo]
endpoint             = "wss://rococo-rpc.polkadot.io"

[pangolin_parachain]
endpoint             = "wss://pangolin-parachain-rpc.darwinia.network"
signer               = "//Alice"

[relay]
lanes            = ["70616c69"]
para_id          = 2105
enable_mandatory = false

[index]
pangolin           = { endpoint = "https://api.subquery.network/sq/darwinia-network/subql-bridge-s2s-pangolin" }
rococo             = { endpoint = "https://api.subquery.network/sq/darwinia-network/subql-bridge-s2s-rococo" }
pangolin_parachain = { endpoint = "https://api.subquery.network/sq/fewensa/subql-bridge-s2s-pangolin-parachain" }
parachain_rococo   = { endpoint = "https://api.subquery.network/sq/darwinia-network/subql-parachain-rococo" }
