[pangolin]
endpoint = "wss://pangolin-rpc.darwinia.network"
signer   = "//Alice"

[pangoro]
endpoint = "wss://pangoro-rpc.darwinia.network"
signer   = "//Alice"

[relay]
lanes            = ["726f6c69"]
enable_mandatory = false

[index]
pangolin = { endpoint = "https://subql.darwinia.network/subql-bridger-pangolin" }
pangoro  = { endpoint = "https://subql.darwinia.network/subql-bridger-pangoro" }

