[pangoro]
endpoint = "https://pangoro-rpc.darwinia.network"
contract_address = "0x9920317f841F3653464bf37512c939744502CA74"
execution_layer_contract_address = "0x99B9C72c93EBC472Ce1A27e064067E78FDcb36E9"
private_key = "//Alice"

[kiln]
endpoint = "http://localhost:5052"
