[pangolin]
endpoint             = "wss://pangolin-rpc.darwinia.network"
signer               = "//Alice"

[rococo]
endpoint             = "wss://rococo-rpc.polkadot.io"

[pangolin_parachain]
endpoint             = "wss://pangolin-parachain-rpc.darwinia.network"
signer               = "//Alice"

[relay]
lanes            = ["70616c69"]
para_id          = 2105
enable_mandatory = false

[index]
pangolin           = { endpoint = "https://subql.darwinia.network/subql-bridger-pangolin" }
rococo             = { endpoint = "https://subql.darwinia.network/subql-bridger-rococo" }
pangolin_parachain = { endpoint = "https://subql.darwinia.network/subql-bridger-pangolin-parachain" }
