[general]
# Whether to relay beacon chain header to evm chain
enable_beacon_header_relay = true
# Whether to relay sync commit from beacon chain to evm chain
enable_sync_commit_relay = true
# Whether to sign the messages root and relay headers from evm chain to beacon chain
enable_ecdsa_relay = true
# Whether to relay messages from execution chain to evm chain
enable_message_execution_to_evm = true
# Whether to relay messages from evm chain to execution chain
enable_message_evm_to_execution = true
# Max number of messages every delivery
max_message_num_per_relaying = 15
# Minimum seconds between two header relay
header_relay_minimum_interval = 900

[darwinia_evm]
endpoint                        = "https://rpc.darwinia.network"
chain_message_committer_address = "0x1829ee0c5E556D50cb4c11791777afd7fF00019a"
contract_address                = "0x0b51a80A37dD1629FcE060BBec6D9fcDB7eFcCfd"
fee_market_address              = "0x9bd2F907B33E25126CD4e4342a75dE8F8eff76Bf"
inbound_address                 = "0x1cE84Cc75847374Ae41B4c1070d5B42A06BB42E7"
lane_message_committer_address  = "0xb1a9585B0739F6ad91d8647699420d7284B71C10"
outbound_address                = "0x7e10D91862E7477C0FedE95D291f7101AE1Aec4d"
# private_key in format of 0x... or ...
private_key = "..."
# Max gas price bridger would use, if eth_gasPrice returns a bigger one. Unit is wei.
max_gas_price = 25000000000000 # 25000 Gwei

[darwinia_substrate]
endpoint = "wss://rpc.darwinia.network"
# private_key in format of 0x... or ..., 
# this should equal to the private_key in darwinia_evm, if you are the member of ECDSA authority.
private_key = "..."

[beacon]
# Beacon chain api endpoint and api supplier
api_supplier = "Nimbus"
endpoint     = "https://lodestar-mainnet.chainsafe.io"

[ethereum]
# Execution layer api endpoint, register one at https://dashboard.alchemy.com/
endpoint           = "..."
fee_market_address = "0xC71593F6Cb1642DD95bd1330f7c0a59d9f66Db97"
inbound_address    = "0x9bd2F907B33E25126CD4e4342a75dE8F8eff76Bf"
outbound_address   = "0x171A87e3969fC82c8d25A0866316FCc6378B5c10"
# private_key in format of 0x... or ...
posa_light_client_address = "0x2802E5fa6251B1D0Be2aE57cD1e17422B5B35839"
private_key               = "..."
# Max gas price bridger would use, if eth_gasPrice returns a bigger one. Unit is wei.
max_gas_price = 20000000000 # 20 Gwei
# Bridger use etherscan gas oracle to get more appropriate gas price.
# Register to get a free etherescan api key at https://docs.etherscan.io/api-endpoints/gas-tracker
etherscan_api_key = "api_key..."

[index]
evm_chain       = { endpoint = "https://thegraph.darwinia.network/ethv2/subgraphs/name/bridge-darwinia" }
substrate_chain = { endpoint = "https://subql.darwinia.network/subql-bridger-darwinia/" }
