encrypted: false
ethereum:
  # ethereum json-rpc endpoint
  rpc: https://mainnet.infura.io/v3/<YOUR_KEY>
  contract:
    ring:
      # erc20 contract of ring
      address: 0x9469d013805bffb7d3debe5e7839237e535ec483
      topics:
        # cross transfer topic
        - 0xc9dcda609937876978d7e0aa29857cb187aea06ad9e843fd23fd32108da73f10
    kton:
      # erc20 contract of kton
      address: 0x9f284e1337a815fe77d2ff4ae46544645b20c5ff
      topics:
        # cross transfer topic
        - 0xc9dcda609937876978d7e0aa29857cb187aea06ad9e843fd23fd32108da73f10
    bank:
      # gringotts bank contract
      address: 0x649fdf6ee483a96e020b889571e93700fbd82d88
      topics:
        # cross transfer topic
        - 0xe77bf2fa8a25e63c1e5e29e1b2fcb6586d673931e020c4e3ffede453b830fb12
    issuing:
      # erc20 ring and kton issuing contract
      address: 0xea7938985898af7fd945b03b7bc2e405e744e913
    relay:
      # ethereum relay contract for darwinia to ethereum
      address: 0x5cde5Aafeb8E06Ce9e4F94c2406d3B6CB7098E49
      topics:
        # set authorities topic
        - 0x91d6d149c7e5354d1c671fe15a5a3332c47a38e15e8ac0339b24af3c1090690f
  # (optional) the person who will relay darwinia data to ethereum
  # Disable by removing or commenting
  relayer:
    # private key of relayer
    private_key: 0x...
    # the darwinia account public key who will get the reward
    # when send authorities to ethereum
    beneficiary_darwinia_account: 0x...
  # (optional) the person who will ecdsa sign new mmr root or new authority set
  # Disable by removing or commenting
  authority:
    # private key to sign ecdsa messages
    # the signature will be submitted to Darwinia by darwinia.relayer
    private_key: 0x...

darwinia:
  # darwinia node websocket json-rpc endpoint
  rpc: wss://rpc.darwinia.network
  # the person who will relay ethereum data to darwinia
  relayer:
    # private key of relayer, or, private key of proxy
    private_key: 0x...
    # (optional) real account public key
    # allowing `real` account to give permission to `proxy` account to dispatch calls
    # The account (32 bytes) that the proxy will make a call on behalf of
    # Disable by removing or commenting
    real_account: 0x...

shadow:
  # shadow http restful endpoint, refer https://github.com/darwinia-network/shadow
  endpoint: https://shadow.darwinia.network

services:
  ethereum:
    # ethereum service polling interval in seconds
    step: 120
  relay:
    # relay service polling interval in seconds
    step: 60
  redeem:
    # redeem service polling interval in seconds
    step: 150
  guard:
    # guard service polling interval in seconds
    step: 30
