[darwinia]
# a offchain-indexing opening pangolin node
endpoint = "wss://pangolin-rpc.darwinia.network"

# private key of relayer, or, private key of proxy
relayer_private_key = "0x..."
# (optional) real account public key
relayer_real_account = "0x..."

# private key to sign ecdsa messages
ecdsa_authority_private_key = "0x..."

strict = false

[web3]
endpoint = "https://ropsten.infura.io/v3/<YOUR_KEY>"

[ethereum]
# below two need to be all setted if you want to do the relay job
# (optional) the person who will relay darwinia data to ethereum
relayer_private_key = "0x..."
# (optional) the darwinia account public key who will get the reward
relayer_beneficiary_darwinia_account = "0x..."

# listen to set authorities
subscribe_relay_address = "0xd374292D512281b56198F0401b149370D680b89F"

[shadow]
endpoint = "https://ropsten.shadow.darwinia.network"

[task]
interval_ethereum = 120
interval_relay = 60
interval_guard = 30
interval_check = 90
check_timeout = 2000

[http_client]
timeout = 3000

[thegraph]
endpoint = "https://api.thegraph.com/subgraphs/name/fewensa/bridge-ropsten"
