[package]
name = "relay-millau-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec                  = { package = "parity-scale-codec", version = "2.0.0" }
headers-relay          = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.2" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.2" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.2" }

# Supported Chains

millau-runtime      = { git = "https://github.com/darwinia-network/darwinia-launch.git", branch = "s2s" }
millau-primitives   = { git = "https://github.com/darwinia-network/darwinia-launch.git", branch = "s2s" }

# Substrate Dependencies

frame-support              = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.2" }
frame-system               = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.2" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.2" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.2" }
sp-keyring                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.2" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.2" }
