[package]
name = "client-pangoro"
version = "0.6.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
tracing = "0.1"
thiserror = "1"

serde       = { version = "1", features = ["derive"] }
serde_json  = "1"

array-bytes = "2"
codec       = { package = "parity-scale-codec", version = "2" }
subxt       = { git = "https://github.com/darwinia-network/subxt.git", branch = "darwinia-v0.12.3" }
bp-pangoro  = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.3" }

## maybe common
async-trait           = { optional = true, version = "0.1" }

## substrate
sp-finality-grandpa = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.3" }
sp-runtime          = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.3" }
sp-core             = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.3" }

## s2s client
finality-grandpa      = { optional = true, version = "0.14" }
bridge-s2s-traits   = { optional = true, path = "../../../frame/traits/bridge-s2s", features = ["advanced-types"] }

## feemarket s2s
feemarket-s2s-traits = { optional = true, path = "../../../frame/traits/feemarket-s2s", features = ["advanced-types"] }

support-toolkit  = { path = "../../../frame/supports/support-toolkit", features = ["convert"] }

[features]
default     = []
substrate   = [
  "sp-finality-grandpa",
  "sp-runtime",
  "sp-core",
]
bridge-s2s         = [
  "substrate",
  "async-trait",
  "finality-grandpa",
  "bridge-s2s-traits",
]
bridge-s2s-pangolin = ["bridge-s2s"]
feemarket-s2s   = [
  "async-trait",
  "feemarket-s2s-traits",
]
feemarket-s2s-pangolin = ["feemarket-s2s"]
bridge-chapel = []

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

