[package]
name = "client-pangoro"
version = "0.5.7"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
tracing = "0.1"
thiserror = "1"

serde       = { version = "1", features = ["derive"] }
serde_json  = "1"

array-bytes = "1.4"
codec       = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full"] }
subxt       = { git = "https://github.com/darwinia-network/subxt.git", branch = "darwinia-v0.12.2" }

## s2s client
async-trait         = { version = "0.1", optional = true }
finality-grandpa    = { version = "0.14.0", optional = true }
bp-header-chain     = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.2", optional = true }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.2", optional = true }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.2", optional = true }
abstract-client-s2s = { path = "../../../frame/abstract/client-s2s", optional = true }

support-toolkit  = { path = "../../../frame/supports/support-toolkit" }

[features]
default      = []
s2s          = [
  "async-trait",
  "finality-grandpa",
  "bp-header-chain",
  "sp-finality-grandpa",
  "sp-runtime",
  "abstract-client-s2s",
]
s2s-pangolin = ["s2s"]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

