[package]
name = "component-pangoro-s2s"
version = "0.4.7"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
log = "0.4"

bridge-traits = { path = "../../traits" }

codec                  = { package = "parity-scale-codec", version = "2.0.0" }
headers-relay          = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-rc1" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-rc1" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-rc1" }
messages-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-rc1" }
bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-rc1" }
bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-rc1" }


## Bridge dependencies
pangoro-runtime         = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s" }
common-primitives       = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s" }
bridge-primitives       = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s" }
pangoro-constants       = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s" }
dp-fee                  = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "s2s" }



## Substrate Dependencies
frame-system               = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6" }
frame-support              = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6" }
sp-keyring                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6" }

