specVersion: 0.2.0
name: bridge-s2s-crab
version: 0.0.4
description: S2S bridge crab subql
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql

network:
  genesisHash: '0x34f61bfda344b3fad3c3e38832a91448b3c613b199eb23e5110a635d71c13c65'
  endpoint: wss://crab-rpc.darwinia.network

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 10784800
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler

        - handler: handleCall
          kind: substrate/CallHandler

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: grandpa
            method: NewAuthorities

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabParachainMessages
            method: MessageAccepted

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabParachainDispatch

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaMessages
            method: MessageAccepted

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
