[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE", "src/BSCValidatorSet_abi.json"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "bridge-darwinia-ethereum"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.7.3"

[[bin]]
name = "bridge-darwinia-ethereum"
path = "src/main.rs"

[dependencies]
color-eyre  = "0.6"
tracing     = "0.1"
tokio       = { version = "1", features = ["full"] }
serde     = { version = "1", features = ["derive"] }
structopt = "0.3"

support-common     = { path = "../../frame/supports/support-common" }
support-command-kv = { path = "../../frame/supports/support-command-kv" }
component-state       = { path = "../../frame/components/state" }

bridge-e2e-traits     = { path = "../../traits/bridge-e2e" }
subquery              = { path = "../../assistants/subquery", features = [ "bridge-ethv2" ] }
client-darwinia       = { path = "../../assistants/client-darwinia", features = [ "bridge-e2e" ] }
relay-e2e             = { path = "../../assistants/relay-e2e" }
thegraph              = { path = "../../assistants/thegraph", features = [ "bridge-ethv2" ] }
bin-e2e               = { path ="../../assistants/bin-e2e" }


[patch.crates-io]
eth2_hashing     = { git = "https://github.com/sigp/lighthouse", tag = "v3.5.1" }
eth2_serde_utils = { git = "https://github.com/sigp/lighthouse", tag = "v3.5.1" }
eth2_ssz         = { git = "https://github.com/sigp/lighthouse", tag = "v3.5.1" }
eth2_ssz_derive  = { git = "https://github.com/sigp/lighthouse", tag = "v3.5.1" }
eth2_ssz_types   = { git = "https://github.com/sigp/lighthouse", tag = "v3.5.1" }
tree_hash        = { git = "https://github.com/sigp/lighthouse", tag = "v3.5.1" }
tree_hash_derive = { git = "https://github.com/sigp/lighthouse", tag = "v3.5.1" }
