[package]
edition = "2021"
name    = "pangolin-parachain-subxt"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#codec = { package = "parity-scale-codec", version = "2", default-features = false, features = [
#    "derive",
#    "full",
#    "bit-vec",
#] }
subxt     = "0.17"
