[package]
name = "pangoro-subxt"
version = "0.5.5"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]


subxt       = { git = "https://github.com/paritytech/subxt.git" }
codec       = { package = "parity-scale-codec", version = "2.3.1", default-features = false, features = ["derive", "full"] }

