[package]
name = "support-etherscan"
version = "0.8.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
tracing     = "0.1"
async-trait = "0.1"
tokio       = { version = "1", features = ["full"] }
thiserror   = "1.0"
web3        = { version = "0.18.0" }
reqwest     = { version = "0.11", features = ["json"] }
serde       = { version = "1", features = ["derive"] }
serde_json  = { version = "1.0.85" }

