[workspace]
members = [
	"bridge",
	"client-pangolin",
	"client-pangoro",
]

# TODO: Remvoe this in `v2.8.5`
[patch.crates-io]
evm           = { git = "https://github.com/darwinia-network/evm", branch = "v0.30.1" }
evm-gasometer = { git = "https://github.com/darwinia-network/evm", branch = "v0.30.1" }
evm-runtime   = { git = "https://github.com/darwinia-network/evm", branch = "v0.30.1" }
