[package]
name = "bridge-pangolin-pangoro"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]

tracing = "0.1"
color-eyre = "0.5"

async-trait = "0.1"

tokio = { version = "1", features = ["full"] }
colored     = "2"
structopt   = "0.3"
strum       = { version = "0.21", features = ["derive"] }

codec = { package = "parity-scale-codec", version = "2.3.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
futures = "0.3"
futures-timer = "3"

lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage = "0.4"

## Substrate Dependencies

frame-support       = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-core             = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-trie             = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-version          = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }

## bridge common

bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "patch-duplicate-relay" }
bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "patch-duplicate-relay" }
bp-header-chain        = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "patch-duplicate-relay" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "patch-duplicate-relay" }
substrate-relay-helper = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "patch-duplicate-relay" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "patch-duplicate-relay" }
bridge-runtime-common  = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "patch-duplicate-relay" }
pallet-bridge-messages = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "patch-duplicate-relay" }
messages-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "patch-duplicate-relay" }


## component
client-pangolin        = { path = "../client-pangolin" }
client-pangoro         = { path = "../client-pangoro" }
component-subscan      = { path = "../../../frame/components/subscan" }

## support
support-common     = { path = "../../../frame/supports/support-common" }
support-lifeline   = { path = "../../../frame/supports/support-lifeline" }
support-terminal   = { path = "../../../frame/supports/support-terminal" }

## darwinia common
drml-common-primitives  = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.4" }
drml-bridge-primitives  = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.4" }

## pangolin
pangolin-runtime               = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.4", features = ["no-wasm"] }

## pangoro
pangoro-runtime                = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.4", features = ["no-wasm"] }
