[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "bridge-pangolin-pangoro"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.7"

[dependencies]
tracing    = "0.1"
color-eyre = "0.5"

array-bytes = "1.4"
tokio       = { version = "1", features = ["full"] }

structopt = "0.3"
strum     = { version = "0.21", features = ["derive"] }
serde     = { version = "1", features = ["derive"] }
codec     = { package = "parity-scale-codec", version = "2", default-features = false }

lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage  = "0.4"

sp-core     = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.2" }

subxt       = { git = "https://github.com/darwinia-network/subxt.git", branch = "darwinia-v0.12.2" }

support-common     = { path = "../../../frame/supports/support-common" }
support-lifeline   = { path = "../../../frame/supports/support-lifeline" }
support-terminal   = { path = "../../../frame/supports/support-terminal" }

component-http-client = { path = "../../../frame/components/http-client" }

abstract-client-s2s = { path = "../../../frame/abstract/client-s2s" }
client-pangolin     = { path = "../../../frame/assistants/client-pangolin", features = [ "s2s-pangoro" ]}
client-pangoro      = { path = "../../../frame/assistants/client-pangoro", features = [ "s2s-pangolin" ]}
subquery-s2s        = { path = "../../../frame/assistants/subquery-s2s" }
relay-s2s           = { path = "../../../frame/assistants/relay-s2s" }
