[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "pangolin-subxt"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.5"

[dependencies]

thiserror = "1"
array-bytes = "1.4"

#codec = { package = "parity-scale-codec", version = "2", default-features = false, features = [
#  "derive",
#  "full",
#  "bit-vec",
#] }

codec = { package = "parity-scale-codec", version = "2" }
serde = { version = "1", features = ["derive"] }

web3  = { git = "https://github.com/wuminzhe/rust-web3.git", branch = "master" }
subxt = { git = "https://github.com/darwinia-network/subxt.git", branch = "darwinia-v0.12.1" }

component-shadow = { path = "../../components/shadow" }

