[package]
name = "client-pangolin"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]

tracing = "0.1"
color-eyre = "0.5"

codec                  = { package = "parity-scale-codec", version = "2.3.1" }

relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.12.1" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.12.1" }

bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.12.1" }
bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.12.1" }

## Bridge dependencies
pangolin-runtime         = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.3" }
drml-common-primitives   = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.3" }
drml-bridge-primitives   = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.3" }
darwinia-bridge-ethereum = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.3" }
dp-fee                   = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.3" }

## Substrate Dependencies
frame-system               = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
frame-support              = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }


[dev-dependencies]
color-eyre   = "0.5"
futures-test = "0.3"
tokio        = { version = "1", features = ["time"] }
codec        = { package = "parity-scale-codec", version = "2.3.1" }
