[package]
name = "support-config"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]
color-eyre = "0.5"

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-attributes = "0.1"


strum = { version = "0.21", features = ["derive"] }
dirs = "4"

config = "0.11"
serde = "1"
serde_yaml = "0.8"
serde_json = "1"
toml = "0.5"
serde-hjson = "0.9"

support-common = { path = "../support-common" }

