[package]
name = "component-darwinia-s2s"
version = "0.4.7"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
log = "0.4"

bridge-traits = { path = "../../traits" }

codec                  = { package = "parity-scale-codec", version = "2.0.0" }
headers-relay          = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
messages-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }

## Bridge dependencies
darwinia-runtime         = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.11.6" }
common-primitives        = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.11.6" }
bridge-primitives        = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.11.6" }
darwinia-bridge-ethereum = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.6-3" }
#pangolin-constants       = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.6-3" }
dp-fee                  = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.6-3" }



## Substrate Dependencies
frame-system               = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
frame-support              = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
sp-keyring                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }


[dev-dependencies]
anyhow       = "1"
futures-test = "0.3"
tokio        = { version = "1", features = ["time"] }
codec        = { package = "parity-scale-codec", version = "2.2.0" }

