specVersion: 0.2.0
name: bridge-s2s-pangolin-parachain
version: 0.0.4
description: S2S bridge pangolin parachain subql
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql

network:
  endpoint: wss://pangolin-parachain-rpc.darwinia.network/
  genesisHash: '0x9426ba4cc73993fc77e77221f797573dc5c63d418d0478a0a01fab9798fdcceb'

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            - module: bridgePangolinMessages
              method: MessageAccepted
        - handler: handleCall
          kind: substrate/CallHandler
