[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "feemarket-s2s"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.5"

[dependencies]

async-trait = "0.1"
serde       = { version = "1", features = ["derive"] }
thiserror   = "1.0"
tracing     = "0.1"

codec = { package = "parity-scale-codec", version = "2.3.1" }

bp-messages            = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
messages-relay         = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
relay-substrate-client = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
relay-utils            = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }

darwinia-fee-market = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.7" }

## Substrate Dependencies
frame-support = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-core       = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-runtime    = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }


component-subscan = { path = "../../components/subscan" }


# Substrate Dependencies

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

relay-pangolin-client = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
