[package]
name = "support-tracker-evm-log"
version = "0.4.6"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
    "Cargo.toml",
    "**/*.rs",
    "README.md",
    "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
log = "0.4.11"
thiserror = "1"
anyhow = "1"
array-bytes = "1.1"
async-trait = "0.1"

tokio = { version = "1", features = ["full"] }
web3 = { version = "0.16.0", git = "https://github.com/wuminzhe/rust-web3.git", branch = "master", features = ["signing"] }

component-state = { path = "../../components/state" }

support-tracker = { path = "../support-tracker" }
