[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "client-rococo"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.5"

[dependencies]
thiserror = "1"
tracing   = "0.1"

serde      = { version = "1", features = ["derive"] }
serde_json = "1"

array-bytes = "1.4"

codec     = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
secp256k1 = { version = "0.20", features = ["recovery"] }
subxt     = { git = "https://github.com/paritytech/subxt.git", branch = "master" }
web3      = { git = "https://github.com/wuminzhe/rust-web3.git", branch = "master", features = ["signing"] }

rococo-subxt = { path = "../rococo-subxt" }
