[package]
name = "support-s2s"
version = "0.4.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
    "Cargo.toml",
    "**/*.rs",
    "README.md",
    "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
anyhow = "1.0"
log = "0.4"
codec = { package = "parity-scale-codec", version = "2.0.0" }
async-trait = "0.1"
num-traits = "0.2"
futures = "0.3"
async-std = "1.9"
paste = "1.0"
hex = "0.4"
serde = { version = "1", features = ["derive"] }

strum = { version = "0.21", features = ["derive"] }

# Bridge dependencies

bp-header-chain        = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bp-message-dispatch    = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bridge-runtime-common  = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
finality-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
headers-relay          = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
messages-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
pallet-bridge-messages = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
finality-grandpa       = { version = "0.14.0" }


# Substrate Dependencies

frame-support       = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-core             = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-trie             = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-version          = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }



## pangolin
pangolin-runtime                = { optional = true, git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
drml-primitives                 = { optional = true, git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
pangolin-constants              = { optional = true, git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
pangolin-bridge-primitives      = { optional = true, git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
pangolin-runtime-system-params  = { optional = true, git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
component-pangolin              = { optional = true, path = "../../components/client-pangolin" }

## millau
millau-runtime      = { optional = true, git = "https://github.com/darwinia-network/darwinia-launch.git", branch = "pangolin-bridge" }
millau-primitives   = { optional = true, git = "https://github.com/darwinia-network/darwinia-launch.git", branch = "pangolin-bridge" }
component-millau    = { optional = true, path = "../../components/client-millau" }


[features]
default = []
millau = [
    "millau-runtime",
    "component-millau",
    "millau-primitives",
]
pangolin = [
    "pangolin-runtime",
    "component-pangolin",
    "drml-primitives",
    "pangolin-constants",
    "pangolin-bridge-primitives",
    "pangolin-runtime-system-params",
]
