[package]
name = "component-darwinia"
version = "0.4.1"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
    "Cargo.toml",
    "**/*.rs",
    "README.md",
    "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }

codec = { package = "parity-scale-codec", version = "2.1", features = ["derive", "full"] }

bridge-traits = { path = "../../traits" }

bee-client = { git = "https://github.com/darwinia-network/substrate-api-client.git", branch = "bee-v12" }

sp-core = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }


