[package]
name = "client-rococo"
version = "0.5.1"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://rust-docs.darwinia.network/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2021"

[dependencies]

tracing = "0.1"
color-eyre = "0.5"
async-trait = "0.1"

codec                  = { package = "parity-scale-codec", version = "2.3.1" }

relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.12.1" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.12.1" }
bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.12.1" }
bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.12.1" }
messages-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "darwinia-v0.12.1" }

## Bridge dependencies
rococo-runtime         = { git = "https://github.com/paritytech/polkadot.git", branch = "release-v0.9.17" }
drml-common-primitives  = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "support-pangolin-parachain" }
drml-bridge-primitives  = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "support-pangolin-parachain" }
dp-fee                  = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "support-pangolin-parachain" }

## Substrate Dependencies
frame-system               = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
frame-support              = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
