[package]
name = "task-darwinia-crab"
version = "0.4.8"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
log = "0.4"
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
futures = "0.3"
futures-timer = "3"

strum = { version = "0.21", features = ["derive"] }

lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage = "0.4"

bridge-traits = { path = "../../traits" }
support-keep  = { path = "../../supports/support-keep" }

## Substrate Dependencies

frame-support       = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
sp-core             = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
sp-trie             = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }
sp-version          = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.6-1" }

## bridge common

bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
bp-header-chain        = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
substrate-relay-helper = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
bridge-runtime-common  = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
pallet-bridge-messages = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }
messages-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", tag = "darwinia-v0.11.6-3" }


## component
component-darwinia-s2s = { path = "../../components/client-darwinia-s2s" }
component-crab-s2s     = { path = "../../components/client-crab-s2s" }
component-subscan      = { path = "../../components/subscan" }

## darwinia common
bridge-primitives        = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.11.6" }
common-primitives        = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.11.6" }
darwinia-runtime-common  = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.11.6" }

## darwinia
darwinia-runtime               = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.11.6" }

## crab
crab-runtime                   = { git = "https://github.com/darwinia-network/darwinia.git", tag = "v0.11.6" }

