[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "client-pangolin"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.7"

[dependencies]
thiserror = "1"
tracing   = "0.1"

serde       = { version = "1", features = ["derive"] }
serde_json  = "1"

array-bytes = "1.4"
codec       = { package = "parity-scale-codec", version = "2" }
subxt       = { git = "https://github.com/darwinia-network/subxt.git", branch = "darwinia-v0.12.2" }

web3          = { git = "https://github.com/wuminzhe/rust-web3.git", branch = "master", features = ["signing"], optional = true }
secp256k1     = { version = "0.20", features = ["recovery"], optional = true }
shadow-liketh = { path = "../shadow-liketh", optional = true }

async-trait         = { version = "0.1", optional = true }
finality-grandpa    = { version = "0.14.0", optional = true }
bp-header-chain     = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "darwinia-v0.12.2", optional = true }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.2", optional = true }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.2", optional = true }
abstract-client-s2s = { path = "../../../frame/abstract/client-s2s", optional = true }

support-toolkit  = { path = "../../../frame/supports/support-toolkit" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default     = []
ethlike-v1  = ["web3", "secp256k1", "shadow-liketh"]
s2s         = [
  "async-trait",
  "finality-grandpa",
  "bp-header-chain",
  "sp-finality-grandpa",
  "sp-runtime",
  "abstract-client-s2s",
]
s2s-pangoro = ["s2s"]
