[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "client-pangolin"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.7"

[dependencies]
thiserror = "1"
tracing   = "0.1"

serde       = { version = "1", features = ["derive"] }
serde_json  = "1"

array-bytes = "1.4"
codec       = { package = "parity-scale-codec", version = "2" }
subxt       = { git = "https://github.com/darwinia-network/subxt.git", branch = "darwinia-v0.12.2" }

## substrate
sp-finality-grandpa = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.2" }
sp-runtime          = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.2" }
sp-core             = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.2" }

## eth-v1
web3          = { optional = true, git = "https://github.com/wuminzhe/rust-web3.git", branch = "master", features = ["signing"] }
secp256k1     = { optional = true, version = "0.20", features = ["recovery"] }
shadow-liketh = { optional = true, path = "../shadow-liketh" }

## s2s client
async-trait           = { optional = true, version = "0.1" }
finality-grandpa      = { optional = true, version = "0.14" }
abstract-client-s2s   = { optional = true, path = "../../../frame/abstract/client-s2s" }

support-toolkit  = { path = "../../../frame/supports/support-toolkit" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default     = []
substrate   = [
  "sp-finality-grandpa",
  "sp-runtime",
  "sp-core",
]
ethlike-v1  = ["web3", "secp256k1", "shadow-liketh"]
s2s         = [
  "substrate",
  "async-trait",
  "finality-grandpa",
  "abstract-client-s2s",
]
s2s-pangoro = ["s2s"]
