specVersion: 1.0.0
name: subql-s2s-darwinia
version: 0.5.7
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: S2S bridge crab subql
repository: 'https://github.com/darwinia-network/bridger'
schema:
  file: ./schema.graphql
network:
  chainId: '0x729cb8f2cf428adcf81fe69610edda32c5711b2ff17de747e8604a3587021db8'
  endpoint: 'https://rpc.darwinia.network'
  dictionary: 'https://api.subquery.network/sq/darwinia-network/darwinia-dictionary'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 9149928
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: grandpa
            method: NewAuthorities
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabMessages
            method: MessageAccepted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabDispatch
