[package]
authors       = ["Darwinia Network <hello@darwinia.network>"]
description   = "Darwinia bridger"
documentation = "https://rust-docs.darwinia.network/bridger"
edition       = "2021"
homepage      = "https://github.com/darwinia-network/bridger"
include       = ["Cargo.toml", "**/*.rs", "README.md", "LICENSE"]
keywords      = ["substrate", "darwinia"]
license       = "MIT"
name          = "bridge-pangolin-rococo"
readme        = 'README.md'
repository    = "https://github.com/darwinia-network/bridger"
version       = "0.5.5"

[dependencies]

color-eyre = "0.5"
tracing    = "0.1"

async-trait = "0.1"

colored   = "2"
structopt = "0.3"
strum     = { version = "0.21", features = ["derive"] }
tokio     = { version = "1", features = ["full"] }

codec         = { package = "parity-scale-codec", version = "2.3.1" }
futures       = "0.3"
futures-timer = "3"
hex           = "0.4"
serde         = { version = "1", features = ["derive"] }
serde_json    = "1"

lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage  = "0.4"

## Substrate Dependencies

frame-support       = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-core             = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-trie             = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }
sp-version          = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-v0.12.1" }

## bridge common

bp-darwinia-core                = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
bp-header-chain                 = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
bp-messages                     = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
bp-runtime                      = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
bridge-runtime-common           = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
darwinia-fee-market             = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "v2.8.7" }
messages-relay                  = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
pallet-bridge-messages          = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
relay-pangolin-client           = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
relay-pangolin-parachain-client = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
relay-rococo-client             = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
relay-substrate-client          = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
relay-utils                     = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }
substrate-relay-helper          = { git = "https://github.com/darwinia-network/darwinia-bridges-substrate.git", branch = "nada-darwinia-v0.12.1" }

## component
component-subscan = { path = "../../../frame/components/subscan" }
feemarket-s2s     = { path = "../../../frame/assistants/feemarket-s2s" }
client-pangolin   = { path = "../../../frame/assistants/client-pangolin" }

## support
support-common   = { path = "../../../frame/supports/support-common" }
support-lifeline = { path = "../../../frame/supports/support-lifeline" }
support-terminal = { path = "../../../frame/supports/support-terminal" }
