specVersion: 0.2.0
name: bridge-s2s-rococo
version: 0.0.4
description: S2S bridge rococo subql
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql

network:
  endpoint: wss://rococo-rpc.polkadot.io/
  genesisHash: '0x6408de7737c59c238890533af25896a2c20608d8b380bb01029acb392781063e'
  # dictionary: https://api.subquery.network/sq/subquery/kusama-dictionary

dataSources:
  - kind: substrate/Runtime
    startBlock: 544069
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleCall
          kind: substrate/CallHandler
