specVersion: 0.2.0
name: bridge-subql-darwinia
description: Darwinia network
repository: https://github.com/darwinia-network/bridger
schema:
  file: ./schema.graphql

network:
  genesisHash: '0x729cb8f2cf428adcf81fe69610edda32c5711b2ff17de747e8604a3587021db8'
  endpoint: wss://rpc.darwinia.network/
  dictionary: https://api.subquery.network/sq/darwinia-network/darwinia-dictionary

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7200000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereumRelayAuthorities
            method: MMRRootSigned

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereumRelayAuthorities
            method: ScheduleMMRRoot

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereumRelayAuthorities
            method: ScheduleAuthoritiesChange

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereumRelayAuthorities
            method: AuthoritiesChangeSigned
