[package]
name = "task-pangolin-pangoro"
version = "0.4.7"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia bridger"
repository = "https://github.com/darwinia-network/bridger"
license = "MIT"
documentation = "https://docs.rs/bridger"
homepage = "https://github.com/darwinia-network/bridger"
include = [
  "Cargo.toml",
  "**/*.rs",
  "README.md",
  "LICENSE"
]
keywords = ["substrate", "darwinia"]
readme = 'README.md'
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
log = "0.4"
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
futures = "0.3"

strum = { version = "0.21", features = ["derive"] }

lifeline = { git = "https://github.com/fewensa/lifeline-rs.git", branch = "threads-safely" }
postage = "0.4"

bridge-traits = { path = "../../traits" }
support-keep  = { path = "../../supports/support-keep" }

## Substrate Dependencies

frame-support       = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-core             = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-trie             = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }
sp-version          = { git = "https://github.com/darwinia-network/substrate.git", branch = "main" }

## bridge common

bp-runtime             = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bp-messages            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bp-header-chain        = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
relay-substrate-client = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
substrate-relay-helper = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
relay-utils            = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
bridge-runtime-common  = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
pallet-bridge-messages = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }
messages-relay         = { git = "https://github.com/darwinia-network/parity-bridges-common.git", branch = "main" }


## component
component-pangolin-s2s = { path = "../../components/client-pangolin-s2s" }
component-pangoro-s2s  = { path = "../../components/client-pangoro-s2s" }

## darwinia common
common-primitives   = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
bridge-primitives   = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }

## pangolin
pangolin-runtime               = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
pangolin-runtime-system-params = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
pangolin-constants             = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }

## pangoro
pangoro-runtime                = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
pangoro-runtime-system-params  = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
pangoro-constants              = { git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }

