name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-04-15
          override: true
          target: wasm32-unknown-unknown

      - name: Lint
        run: |
          rustup component add clippy
          cargo clippy --all -- -D warnings

      - name: Run tests
        run: cargo test
