name: Check pull request

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-bridger:
    name: Check bridger
    runs-on: ubuntu-latest
    container:
      image: rust:1
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: |
          cd frame
          cargo clippy --release --all -- -D warnings
      - name: Run tests
        run: |
          cd frame
          cargo test --release

      - uses: vishnudxb/cancel-workflow@v1.2
        if: failure()
        with:
          repo: darwinia-network/bridger
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}

  check-bridges:
    name: Check bridge-${{ matrix.bridge }}
    runs-on: ubuntu-latest
    container:
      image: rust:1
    strategy:
      matrix:
        bridge:
          - pangolin-ropsten
          - darwinia-ethereum
          - pangolin-pangoro
          - darwinia-crab
          - pangoro-chapel
          - pangolin-pangolinparachain
          - crab-crabparachain
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: |
          cd bridges/${{ matrix.bridge }}
          cargo clippy --release --all --locked -- -D warnings
      - name: Run tests
        run: |
          cd bridges/${{ matrix.bridge }}
          cargo test --release --locked

      - uses: vishnudxb/cancel-workflow@v1.2
        if: failure()
        with:
          repo: darwinia-network/bridger
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}
