name: Check pull request

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-bridger:
    name: Check bridger
    runs-on: ubuntu-latest
    container:
      image: rust:1
    strategy:
      matrix:
        action:
          - name: Clippy
            run: cargo clippy --locked --all -- -D warnings
          - name: Test
            run: cargo test --locked --all
    steps:
      - uses: actions/checkout@v2

      - name: ${{ matrix.action.name }}
        run: |
          cd frame
          ${{ matrix.action.run }}

      - uses: vishnudxb/cancel-workflow@v1.2
        if: failure()
        with:
          repo: darwinia-network/bridger
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}

  check-bridges:
    name: Check bridge-${{ matrix.bridge }} ${{ matrix.action }}
    runs-on: ubuntu-latest
    container:
      image: rust:1
    strategy:
      matrix:
        action:
          - name: Clippy
            run: cargo clippy --locked --all -- -D warnings
          - name: Test
            run: cargo test --locked --all
        bridge:
          [
            template,
            pangolin-ropsten,
            darwinia-ethereum,
            pangolin-pangoro,
            darwinia-crab,
          ]
    steps:
      - uses: actions/checkout@v2

      - name: ${{ matrix.action.name }}
        run: |
          cd bridges/${{ matrix.bridge }}
          ${{ matrix.action.run }}

      - uses: vishnudxb/cancel-workflow@v1.2
        if: failure()
        with:
          repo: darwinia-network/bridger
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}
