name: Rustdocs

on:
  push:
    tags:
      - 'v*'

env:
  RUST_TOOLCHAIN: nightly


jobs:

  build-frame:
    name: Build rust docs (frame)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Build rust docs
        run: |
          cd frame
          cargo doc --all --no-deps --release

      - name: Collect docs
        run: |
          mkdir rust_docs
          mv frame/target/doc rust_docs/frame

      - name: Upload shared
        uses: actions/upload-artifact@v2
        with:
          name: shared-artifact
          path: rust_docs

  build-bridge:
    name: Build rust docs (${{ matrix.package }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - darwinia-crab
          - darwinia-ethereum
          - pangolin-pangoro
          - pangoro-chapel
          - pangoro-goerli
          - template
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Build rust docs
        run: |
          cd bridges/${{ matrix.package }}
          cargo doc --all --no-deps --release
      - name: Collect docs
        run: |
          mkdir -p rust_docs/bridges
          mv bridges/${{ matrix.package }}/target/doc rust_docs/bridges/${{ matrix.package }}

      - name: Upload shared
        uses: actions/upload-artifact@v2
        with:
          name: shared-artifact
          path: rust_docs


  build-assistants:
    name: Build rust docs (${{ matrix.package }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
         - client-contracts
         - feemarket-s2s
         - relay-e2e
         - relay-s2s
         - subquery
         - thegraph
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Build rust docs
        run: |
          cd assistants/${{ matrix.package }}
          cargo doc --all --no-deps --release
      - name: Collect docs
        run: |
          mkdir -p rust_docs/assistants/
          mv assistants/${{ matrix.package }}/target/doc rust_docs/assistants/${{ matrix.package }}

      - name: Upload shared
        uses: actions/upload-artifact@v2
        with:
          name: shared-artifact
          path: rust_docs


  build-traits:
    name: Build rust docs (${{ matrix.package }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
         - bridge-e2e
         - bridge-s2s
         - feemarket-s2s
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Build rust docs
        run: |
          cd frame/traits/${{ matrix.package }}
          cargo doc --all --no-deps --release
      - name: Collect docs
        run: |
          mkdir rust_docs/traits
          mv frame/traits/${{ matrix.package }}/target/doc rust_docs/traits/${{ matrix.package }}

      - name: Upload shared
        uses: actions/upload-artifact@v2
        with:
          name: shared-artifact
          path: rust_docs


  deploy-rust-docs:
    name: Deploy rust docs
    runs-on: ubuntu-latest
    needs:
      - build-frame
      - build-bridge
      - build-assistants
      - build-traits
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: shared-artifact
          path: rust_docs

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install vercel-ci
        run: npm i -g vercel

      - name: Deploy rust docs
        run: |
          mv .maintain/rust-docs/* rust_docs/
          mv rust_docs bridger
          cd bridger
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering link --confirm
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering deploy --prod

