name: Rustdocs

on:
  push:
    tags:
      - 'v*'

env:
  RUST_TOOLCHAIN: nightly-2021-12-07

jobs:

  build-rust-docs:
    name: Build rust docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Build rust docs
        run: |
          cd frame
          cargo doc --all --no-deps --release
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install vercel-ci
        run: npm i -g vercel
      - name: Deploy rust docs
        run: |
          mv vercel.json frame/target/doc
          mv frame/target/doc frame/target/${GITHUB_REPOSITORY#*/}
          cd frame/target/${GITHUB_REPOSITORY#*/}
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering link --confirm
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering deploy --prod
