name: Rustdocs

on:
  push:
    tags:
      - 'v*'


jobs:

  build-rust-docs:
    name: Build rust docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-04-15
          target: wasm32-unknown-unknown
          default: true
      - name: Build rust docs
        run: cargo doc --all --no-deps --release
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install vercel-ci
        run: npm i -g vercel
      - name: Deploy rust docs
        run: |
          mv vercel.json target/doc
          mv target/doc target/${GITHUB_REPOSITORY#*/}
          cd target/${GITHUB_REPOSITORY#*/}
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering link --confirm
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering deploy --prod

