name: Staging

on:
  workflow_dispatch:

jobs:

  build-publish-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          default: true

      - name: Build bridger
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Collect shared
        run: |
          mkdir -p shared
          mv target/x86_64-unknown-linux-gnu/release/bridger shared/

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io

      - name: Build and publish docker image
        run: |
          IMAGE_NAME=bridger
          IMAGE_PREFIX=quay.io/darwinia-network
          IMAGE_PUSH_NAME_SHA=${IMAGE_PREFIX}/${IMAGE_NAME}:sha-${SHA}

          docker build \
            -t ${IMAGE_NAME} \
            -f .maintain/docker/Dockerfile \
            .

          docker tag ${IMAGE_NAME} ${IMAGE_PUSH_NAME_SHA}

          docker push ${IMAGE_PUSH_NAME_SHA}

