name: Deploy bridger state

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:

jobs:
  deploy-bridger-state:
    name: Deploy bridger state
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - uses: ./.github/actions/smart-vercel
        name: Deploy to Vercel
        id: smart-vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          project_name: bridger-state
          prod_mode: true
          enable_cache: true
          enable_notify_slack: true
          slack_channel: bridger
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
