name: Deploy subgraph develop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-thegraph:
    name: Deploy thegraph
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: [ ethereum, ropsten ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Deploy
        working-directory: thegraph
        run: |
          npm i
          npm run codegen -- subgraph-ropsten.yaml
          npm run build -- subgraph-ropsten.yaml
          npm run deploy -- --access-token ${{ secrets.THEGRAPH_TOKEN_DEV }} \
            fewensa/bridge-${{ matrix.chain }} \
            subgraph-${{ matrix.chain }}.yaml
