name: Deploy subgraph

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ropsten:
    name: Deploy ropsten
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Deploy
        run: |
          cd the-graph
          npm run codegen -- subgraph-ropsten.yaml
          npm run build -- subgraph-ropsten.yaml
          npm run deploy -- --access-token ${{ secrets.THE_GRAPH_TOKEN }} fewensa/bridge-ropsten subgraph-ropsten.yaml
