name: Subquery develop

## IMPORTANT: Please you know, direct push code to master doesn't trigger this action
#  push:
#    branches: [ master ]

on:
  pull_request:
    branches: [ master ]

env:
  SUBQUERY_CLI_VERSION: 0.2.3
  SUBQUERY_ORG: darwinia-network

jobs:
  deploy-subquery:
    name: Deploy subquery
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        chain: [ pangolin, darwinia ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          mkdir -p $HOME/.local/bin
          curl -LO https://github.com/fewensa/subquery-cli/releases/download/v${{ env.SUBQUERY_CLI_VERSION }}/subquery-linux-x86_64.zip
          unzip subquery-linux-x86_64.zip -d $HOME/.local/bin/
          rm -rf subquery-linux-x86_64.zip

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Deploy
        run: |
          set -xe

          subquery --token ${{ secrets.SUBQUERY_TOKEN }} project create \
            --org ${{ env.SUBQUERY_ORG }} \
            --key subql-bridge-${{ matrix.chain }} \
            --repo https://github.com/darwinia-network/bridger \
            --check

          DIFF_SCHEMA=$(git diff \
            ${SHA} \
            origin/master \
            subql/${{ matrix.chain }}/schema.graphql || exit 1)

          echo 'Soft deploy subql/${{ matrix.chain }}'
          subquery --token ${{ secrets.SUBQUERY_TOKEN }} deployment deploy ${DIFF_SCHEMA:+--force} \
            --org ${{ env.SUBQUERY_ORG }} \
            --key subql-bridge-${{ matrix.chain }} \
            --branch ${{ steps.branch-name.outputs.current_branch }} \
            --sub-folder subql/${{ matrix.chain }} \
            --type stage \
            --indexer-image-version v0.28.2 \
            --query-image-version v0.12.0
