name: Deploy subquery develop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RUST_TOOLCHAIN: stable
  SUBQUERY_CLI_VERSION: v0.1.0

jobs:
  deploy-subquery:
    name: Deploy subquery
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: [ pangolin, darwinia ]
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Install dependencies
        run: |
          mkdir -p $HOME/.local/bin
          curl -LO https://github.com/fewensa/subquery-cli/releases/download/${{ env.SUBQUERY_CLI_VERSION }}/subquery-linux-x86_64.zip
          unzip subquery-linux-x86_64.zip -d $HOME/.local/bin/
          rm -rf subquery-linux-x86_64.zip

      - name: Deploy
        run: |
          subquery -h
