name: Test CI

on:
  pull_request:
    branches: [master]


env:
  OPENSSL_DIR: /home/runner/openssl
  OPENSSL_STATIC: 1
  RUST_TOOLCHAIN: nightly

jobs:

  build-win:
    name: Build package [windows]
    runs-on: windows-latest
    steps:
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 1085a57da0725c19e19586025438e8c16f34c890

#      - name: Setup scoop
#        uses: shovel-org/GithubActions@main
#        with:
#          scoop_checkup: true
#          scoop_update: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          vcpkg install openssl:x64-windows-static

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          target: x86_64-pc-windows-msvc

      - name: Build bridger
        run: |
          cd frame
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Collect shared for bridger
        run: |
          mkdir -p shared
          zip -jr \
            shared/bridger-linux-x86_64.zip \
            frame/target/x86_64-unknown-linux-gnu/release/bridger
